version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: presidio-nl:latest
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - pip-cache:/root/.cache/pip
      - model-cache:/app/models
      - pdf-storage:/app/storage
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/models
      - STORAGE_DIR=/app/storage
      - MAX_STORAGE_TIME=3600
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  cli:
    build:
      context: .
      dockerfile: Dockerfile
    image: presidio-nl:latest
    volumes:
      - ./src:/app/src
      - model-cache:/app/models
    environment:
      - TRANSFORMERS_CACHE=/app/models
    command: ["python", "main.py"]
    profiles:
      - cli

volumes:
  pip-cache:
  model-cache:
  pdf-storage: