version: '3.8'

services:
  api:
    container_name: presidio-nl-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: presidio-nl:latest
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - pip-cache:/root/.cache/pip
      - model-cache:/app/models
      - type: volume
        source: api-storage
        target: /app/storage
        volume:
          nocopy: true
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/app/models
      - STORAGE_DIR=/app/storage
      - MAX_STORAGE_TIME=3600
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  cli:
    container_name: presidio-nl-cli
    build:
      context: .
      dockerfile: Dockerfile
    image: presidio-nl:latest
    volumes:
      - ./src:/app/src
      - ./onverwerkt:/app/onverwerkt
      - ./verwerkt:/app/verwerkt
      - model-cache:/app/models
    environment:
      - TRANSFORMERS_CACHE=/app/models
    command: ["python", "main.py"]
    profiles:
      - cli

volumes:
  pip-cache:
    name: presidio-nl-pip-cache
  model-cache:
    name: presidio-nl-model-cache
  api-storage:
    name: presidio-nl-api-storage