# Default values for presidio-nl
replicaCount: 1

image:
  repository: ghcr.io/mwest2020/presidio-nl
  tag: latest
  pullPolicy: IfNotPresent

# Geen imagePullSecrets nodig voor een publieke repository
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Geeft aan dat er een serviceaccount aangemaakt moet worden
  create: true
  annotations: {}
  # Naam wordt automatisch gegenereerd indien leeg
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  # ClusterIP zorgt voor interne toegang binnen het cluster
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    # Connection timeouts
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "2"
    # Keep alive settings
    nginx.ingress.kubernetes.io/upstream-keepalive-connections: "32"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "32"
    nginx.ingress.kubernetes.io/upstream-keepalive-requests: "100"
    # Buffer settings
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "8k"
  hosts:
    - host: api.presidio-nl.conduction.nl
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: conduction-accept-presidio-presidio-nl
              port:
                number: 8000
  tls: []

resources:
  limits:
    cpu: 2000m
    memory: 8Gi
  requests:
    cpu: 1000m
    memory: 4Gi

persistence:
  enabled: true
  # Gebruik de NFS storageclass voor betere prestaties
  storageClass: "nfs"
  size: 25Gi

networkPolicy:
  enabled: false
  allowedNamespaces:
    - presidio

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Applicatie specifieke instellingen
app:
  debug: false
  logLevel: "info"
  api:
    host: "0.0.0.0"
    port: 8000
    # internalOnly op false zorgt ervoor dat er geen restrictie is voor externe toegang
    internalOnly: false
  storage:
    cleanupInterval: 3600  # 1 uur
