# Default values for presidio-nl
replicaCount: 1

image:
  repository: ghcr.io/mwest2020/presidio-nl
  tag: latest
  pullPolicy: IfNotPresent

# No imagePullSecrets needed for public repository
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  # ClusterIP zorgt ervoor dat de service alleen binnen het cluster bereikbaar is
  type: ClusterIP
  port: 8000

ingress:
  # Ingress is uitgeschakeld omdat de API intern beschikbaar moet blijven
  enabled: false
  # Indien je in de toekomst externe toegang wilt toevoegen, kun je hieronder de configuratie aanpassen
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/rewrite-target: /anonymize/text
  hosts:
    - host: api.presidio-nl.conduction.nl
      paths:
        - path: /api/v1/anonymize/text
          pathType: Exact
          backend:
            service:
              name: conduction-accept-presidio-presidio-nl
   
