apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: presidio-nl-storage
  namespace: conduction
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 